### ISSUE TITLE
pybind v2 fails to recognize default value of step argument ?

### ISSUE THREAD

**Issue by faze-geek** [pocketpy/gsoc-2024-dev#74]
Hi, I have tested pybind v2 with `numpy/tests/test_numpy.py`. All the tests bar this one is working 😄 !

https://github.com/pocketpy/gsoc-2024-dev/blob/f7d1813d7e0ff47309f0f9aaab1a5ef91f3a70f6/numpy/tests/test_numpy.py#L624-L631

**Comment by faze-geek** [comment]
This works correctly with original pybind11 executable. @16bit-ykiko Can you have a look. Thanks !

```
(base) anurag@Anurags-MacBook-Air build % python3 
Python 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:46:42) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy_bindings as np
>>> arr1 = np.arange(30).reshape([3, 2, 5])
>>> arr1[1::]
array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],
       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])
>>> arr1[:2:]
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],
       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

```

**Comment by faze-geek** [comment]
With our implementation -
```
>>> import numpy_bindings as np
>>> arr1 = np.arange(30).reshape([3, 2, 5])
>>> arr1[1::]
Traceback (most recent call last):
  File "<stdin>", line 1
    arr1[1::]
SyntaxError: expected an expression, got ]
>>> arr1[:2:]
Traceback (most recent call last):
  File "<stdin>", line 1
    arr1[:2:]
SyntaxError: expected an expression, got ]
```
